language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - mysql
  - postgresql
env:
  - DJANGO=1.10 DB=sqlite
  - DJANGO=1.11 DB=sqlite
  - DJANGO=1.11 DB=mysql
  - DJANGO=1.11 DB=postgres

before_script:
  - mysql -e 'create database pivot;'
  - psql -c 'create database pivot;' -U postgres
install:
  - pip install pip --upgrade
  - if [ "$DB" == "mysql" ]; then pip install mysqlclient; fi
  - if [ "$DB" == "postgres" ]; then pip install psycopg2; fi
  - pip install -q Django==$DJANGO
script:
  - python runtests.py --settings=django_pivot.tests.test_"$DB"_settings