language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - mysql
  - postgresql
env:
  - DJANGO=1.11 DB=sqlite
  - DJANGO=1.11 DB=mysql
  - DJANGO=1.11 DB=postgres
  - DJANGO="https://github.com/django/django/archive/stable/2.0.x.zip" DB=sqlite
matrix:
  exclude:
  - python: "2.7"
    env: DJANGO="https://github.com/django/django/archive/stable/2.0.x.zip"
  - python: "3.4"
    env: DJANGO="https://github.com/django/django/archive/stable/2.0.x.zip"

before_script:
  - mysql -e 'create database joinfield;'
  - psql -c 'create database joinfield;' -U postgres
install:
  - pip install pip --upgrade
  - if [ "$DB" == "mysql" ]; then pip install mysqlclient; fi
  - if [ "$DB" == "postgres" ]; then pip install psycopg2; fi
  - pip install -q Django==$DJANGO
script:
  - python runtests.py --settings=joinfield.tests.test_"$DB"_settings